import Mathlib.Algebra.MvPolynomial.Basic
import Mathlib.Algebra.MvPolynomial.CommRing
import Mathlib.Algebra.MvPolynomial.Eval
import Mathlib.Algebra.Polynomial.Basic
import Mathlib.Algebra.BigOperators.Group.Finset.Basic
import Mathlib.Algebra.BigOperators.GroupWithZero.Finset
import Mathlib.Combinatorics.Nullstellensatz

open BigOperators

/-!
# Phase 1: Algebraic Foundations

This module sets up the algebraic geometry foundations required for the
proof of the Composition Lemma. It heavily utilizes Mathlib's formalization
of Alon's Combinatorial Nullstellensatz.

The core objective is to link the vanishing of a polynomial P(x) on the grid ℤₙⁿ
to its membership in the ideal generated by the falling factorials (x_i)_n.
-/

namespace KRR

variable {n : ℕ}

/--
Falling factorial (x)_n = x(x-1)...(x-n+1) for a single variable in ℤ[X].
This is the univariate polynomial that vanishes exactly on {0, 1, ..., n-1}.
-/
noncomputable def fallingFactorialPoly (n : ℕ) : Polynomial ℤ :=
  ∏ i ∈ Finset.range n, (Polynomial.X - Polynomial.C (i : ℤ))

/--
The multivariate falling factorial (x_i)_n in MvPolynomial (Fin n) ℤ.
-/
noncomputable def mvFallingFactorial (n : ℕ) (i : Fin n) : MvPolynomial (Fin n) ℤ :=
  ∏ k ∈ Finset.range n, (MvPolynomial.X i - MvPolynomial.C (k : ℤ))

/--
The ideal I generated by the falling factorials { (x_i)_n : i ∈ Fin n }
-/
noncomputable def gridIdeal (n : ℕ) : Ideal (MvPolynomial (Fin n) ℤ) :=
  Ideal.span (Set.range (fun i : Fin n => mvFallingFactorial n i))

/--
The finite grid {0, 1, ..., n-1} as a Finset ℤ.
-/
def grid (n : ℕ) : Finset ℤ :=
  (Finset.range n).image (fun (k : ℕ) => (k : ℤ))

/--
If P ∈ I, then P evaluates to 0 on all points in the grid.
-/
theorem eval_eq_zero_of_mem_gridIdeal {n : ℕ} (P : MvPolynomial (Fin n) ℤ)
    (hP : P ∈ gridIdeal n) (x : Fin n → ℤ) (hx : ∀ i, x i ∈ grid n) :
    MvPolynomial.eval x P = 0 := by
  refine Submodule.span_induction ?_ ?_ ?_ ?_ hP
  · rintro _ ⟨i, rfl⟩
    simp only [mvFallingFactorial, map_prod, map_sub, MvPolynomial.eval_X, MvPolynomial.eval_C]
    have hxi := hx i
    rw [grid, Finset.mem_image] at hxi
    obtain ⟨k, hk, heq⟩ := hxi
    -- heq is (k : ℤ) = x i
    exact Finset.prod_eq_zero hk (by simp [← heq])
  · simp only [map_zero]
  · intro P₁ P₂ _ _ ih1 ih2
    simp only [map_add, ih1, ih2, add_zero]
  · intro c P' _ ihP
    simp only [smul_eq_mul, map_mul, ihP, mul_zero]

/--
Combinatorial Nullstellensatz (Ideal Membership):
A polynomial P vanishes on all of ℤ_n^n if and only if P ∈ I.
-/
theorem mem_gridIdeal_iff_eval_zero {n : ℕ} [NeZero n] (P : MvPolynomial (Fin n) ℤ) :
    P ∈ gridIdeal n ↔ (∀ x : Fin n → ℤ, (∀ i, x i ∈ grid n) → MvPolynomial.eval x P = 0) := by
  constructor
  · intro hP x hx
    exact eval_eq_zero_of_mem_gridIdeal P hP x hx
  · intro h_eval
    have h_nonempty : ∀ i : Fin n, (grid n).Nonempty := by
      intro _
      use 0
      simp only [grid, Finset.mem_image, Finset.mem_range]
      use 0
      exact ⟨NeZero.pos n, rfl⟩
    obtain ⟨h, _, hf_eq⟩ := MvPolynomial.combinatorial_nullstellensatz_exists_linearCombination (fun _ => grid n) h_nonempty P h_eval
    rw [hf_eq]
    simp only [Finsupp.linearCombination_apply, Finsupp.sum]
    apply Submodule.sum_mem
    intro i _
    have h_prod_in_ideal : (∏ s ∈ grid n, (MvPolynomial.X i - MvPolynomial.C s)) ∈ gridIdeal n := by
      have h_prod_eq : (∏ s ∈ grid n, (MvPolynomial.X i - MvPolynomial.C s)) = mvFallingFactorial n i := by
        rw [grid, mvFallingFactorial, Finset.prod_image]
        intro x _ y _ hxy
        exact Int.ofNat_inj.mp hxy
      rw [h_prod_eq]
      apply Ideal.subset_span
      exact Set.mem_range_self i
    apply Ideal.mul_mem_left
    exact h_prod_in_ideal

end KRR
